source 'https://rubygems.org'

gem 'pdf-reader'
gem 'tokenizers'

gem 'ruby-openai'

gem 'daru'

gem 'dotenv-rails', groups: [:development, :test]

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem "debug", platforms: %i[ mri mingw x64_mingw ]
end

group :development do
  # Speed up commands on slow machines / big apps [https://github.com/rails/spring]
  # gem "spring"
end

